<<<<<<< HEAD
<<<<<<< HEAD
# HTML
# Archive your static HTML project and save it with the build record.
=======
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
1
=======
# HTML
# Archive your static HTML project and save it with the build record.

# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
<<<<<<< HEAD
<<<<<<< HEAD
=======
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
<<<<<<< HEAD
=======
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

=======

